In [17]:
import pandas as pd

In [18]:
df = pd.read_csv('full.csv')
df.head()

/var/folders/t4/ptp21_653qb6rgtnz9f6_p180000gn/T/ipykernel_18612/662933353.py:1: DtypeWarning: Columns (0: code_commune, 1: code_departement, 2: ancien_nom_commune, 3: ancien_id_parcelle, 4: numero_volume, 5: lot1_numero, 6: lot2_numero, 7: lot3_numero) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('full.csv')

,id_mutation,date_mutation,numero_disposition,nature_mutation,valeur_fonciere,adresse_numero,adresse_suffixe,adresse_nom_voie,adresse_code_voie,code_postal,...,type_local,surface_reelle_bati,nombre_pieces_principales,code_nature_culture,nature_culture,code_nature_culture_speciale,nature_culture_speciale,surface_terrain,longitude,latitude
0,2025-1,2025-01-07,1,Vente,468000.0,NaN,NaN,FARGES,B078,1550.0,...,NaN,NaN,NaN,J,jardins,NaN,NaN,78.0,5.907229,46.170923
1,2025-1,2025-01-07,1,Vente,468000.0,454.0,NaN,RUE DE LA REPUBLIQUE,0090,1550.0,...,Maison,111.0,5.0,S,sols,NaN,NaN,133.0,5.907186,46.170782
2,2025-1,2025-01-07,1,Vente,468000.0,454.0,NaN,RUE DE LA REPUBLIQUE,0090,1550.0,...,Dépendance,NaN,0.0,S,sols,NaN,NaN,133.0,5.907186,46.170782
3,2025-2,2025-01-06,1,Vente,180000.0,NaN,NaN,LE VILLAGE,B158,1200.0,...,NaN,NaN,NaN,S,sols,NaN,NaN,46.0,5.801623,46.164573
4,2025-2,2025-01-06,1,Vente,180000.0,NaN,NaN,LE VILLAGE,B158,1200.0,...,NaN,NaN,NaN,J,jardins,NaN,NaN,17.0,5.801676,46.164610

In [19]:
df['date_mutation'] = pd.to_datetime(df['date_mutation'])
df

,id_mutation,date_mutation,numero_disposition,nature_mutation,valeur_fonciere,adresse_numero,adresse_suffixe,adresse_nom_voie,adresse_code_voie,code_postal,...,type_local,surface_reelle_bati,nombre_pieces_principales,code_nature_culture,nature_culture,code_nature_culture_speciale,nature_culture_speciale,surface_terrain,longitude,latitude
0,2025-1,2025-01-07,1,Vente,468000.0,NaN,NaN,FARGES,B078,1550.0,...,NaN,NaN,NaN,J,jardins,NaN,NaN,78.0,5.907229,46.170923
1,2025-1,2025-01-07,1,Vente,468000.0,454.0,NaN,RUE DE LA REPUBLIQUE,0090,1550.0,...,Maison,111.0,5.0,S,sols,NaN,NaN,133.0,5.907186,46.170782
2,2025-1,2025-01-07,1,Vente,468000.0,454.0,NaN,RUE DE LA REPUBLIQUE,0090,1550.0,...,Dépendance,NaN,0.0,S,sols,NaN,NaN,133.0,5.907186,46.170782
3,2025-2,2025-01-06,1,Vente,180000.0,NaN,NaN,LE VILLAGE,B158,1200.0,...,NaN,NaN,NaN,S,sols,NaN,NaN,46.0,5.801623,46.164573
4,2025-2,2025-01-06,1,Vente,180000.0,NaN,NaN,LE VILLAGE,B158,1200.0,...,NaN,NaN,NaN,J,jardins,NaN,NaN,17.0,5.801676,46.164610
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1387072,2025-502880,2025-06-27,1,Vente,550000.0,84.0,NaN,RUE VERGNIAUD,9679,75013.0,...,Appartement,61.0,3.0,NaN,NaN,NaN,NaN,NaN,2.343663,48.823258
1387073,2025-502881,2025-06-27,1,Vente,550386.1,24.0,NaN,RUE DE PONTOISE,7621,75005.0,...,Appartement,47.0,2.0,NaN,NaN,NaN,NaN,NaN,2.351236,48.849138
1387074,2025-502881,2025-06-27,1,Vente,550386.1,24.0,NaN,RUE DE PONTOISE,7621,75005.0,...,Dépendance,NaN,0.0,NaN,NaN,NaN,NaN,NaN,2.351236,48.849138
1387075,2025-502882,2025-06-25,1,Vente,24417580.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.283008,48.840781
1387076,2025-502882,2025-06-25,1,Vente,24417580.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.283008,48.840781

In [25]:
pd.options.display.float_format = '{:,.0f}'.format

In [26]:
monthly = df.groupby(df['date_mutation'].dt.to_period('M'), as_index=False).agg({'valeur_fonciere': 'mean'})
monthly

  date_mutation  valeur_fonciere
0       2025-01          621,880
1       2025-02          478,419
2       2025-03          578,231
3       2025-04        1,205,798
4       2025-05          518,432
5       2025-06          728,060

In [27]:
monthly_change = monthly.set_index('date_mutation')['valeur_fonciere'].diff()

def trend(x):
    if x > 0:
        return 'hausse'
    if x < 0:
        return 'baisse'
    return 'stable'

trend_map = monthly_change.fillna(0).apply(trend)
df['y'] = df['date_mutation'].dt.to_period('M').map(trend_map)

In [28]:
df

,id_mutation,date_mutation,numero_disposition,nature_mutation,valeur_fonciere,adresse_numero,adresse_suffixe,adresse_nom_voie,adresse_code_voie,code_postal,...,surface_reelle_bati,nombre_pieces_principales,code_nature_culture,nature_culture,code_nature_culture_speciale,nature_culture_speciale,surface_terrain,longitude,latitude,y
0,2025-1,2025-01-07,1,Vente,"468,000",NaN,NaN,FARGES,B078,"1,550",...,NaN,NaN,J,jardins,NaN,NaN,78,6,46,stable
1,2025-1,2025-01-07,1,Vente,"468,000",454,NaN,RUE DE LA REPUBLIQUE,0090,"1,550",...,111,5,S,sols,NaN,NaN,133,6,46,stable
2,2025-1,2025-01-07,1,Vente,"468,000",454,NaN,RUE DE LA REPUBLIQUE,0090,"1,550",...,NaN,0,S,sols,NaN,NaN,133,6,46,stable
3,2025-2,2025-01-06,1,Vente,"180,000",NaN,NaN,LE VILLAGE,B158,"1,200",...,NaN,NaN,S,sols,NaN,NaN,46,6,46,stable
4,2025-2,2025-01-06,1,Vente,"180,000",NaN,NaN,LE VILLAGE,B158,"1,200",...,NaN,NaN,J,jardins,NaN,NaN,17,6,46,stable
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1387072,2025-502880,2025-06-27,1,Vente,"550,000",84,NaN,RUE VERGNIAUD,9679,"75,013",...,61,3,NaN,NaN,NaN,NaN,NaN,2,49,hausse
1387073,2025-502881,2025-06-27,1,Vente,"550,386",24,NaN,RUE DE PONTOISE,7621,"75,005",...,47,2,NaN,NaN,NaN,NaN,NaN,2,49,hausse
1387074,2025-502881,2025-06-27,1,Vente,"550,386",24,NaN,RUE DE PONTOISE,7621,"75,005",...,NaN,0,NaN,NaN,NaN,NaN,NaN,2,49,hausse
1387075,2025-502882,2025-06-25,1,Vente,"24,417,580",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,49,hausse
1387076,2025-502882,2025-06-25,1,Vente,"24,417,580",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,49,hausse

In [29]:
df['y'].value_counts()

y
hausse    723736
baisse    412169
stable    251172
Name: count, dtype: int64

In [ ]:
X = df.drop(columns=['y'])
y = df['y']

X_train = X[X['date_mutation'] < '2023-01']
y_train = y[X['date_mutation'] < '2023-01']

X_test = X[X['date_mutation'] >= '2023-01']
y_test = y[X['date_mutation'] >= '2023-01']