In [ ]:
import os
os.chdir("..")  # ← remonte dans data-pipeline/
print(os.getcwd())  # vérification

c:\Users\Utilisateur\Desktop\projects\GeoLogis\data-pipeline

In [ ]:
import pandas as pd

In [11]:
df = pd.read_csv('raw/communes-france-2025.csv')
df

C:\Users\Utilisateur\AppData\Local\Temp\ipykernel_17420\1818052200.py:1: DtypeWarning: Columns (1,12,14,16,23,24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('raw/communes-france-2025.csv')

,Unnamed: 0,code_insee,nom_standard,nom_sans_pronom,nom_a,nom_de,nom_sans_accent,nom_standard_majuscule,typecom,typecom_texte,...,longitude_mairie,latitude_centre,longitude_centre,grille_densite,grille_densite_texte,niveau_equipements_services,niveau_equipements_services_texte,gentile,url_wikipedia,url_villedereve
0,0,01001,L'Abergement-Clémenciat,Abergement-Clémenciat,à Abergement-Clémenciat,de l'Abergement-Clémenciat,l-abergement-clemenciat,L'ABERGEMENT-CLÉMENCIAT,COM,commune,...,4.921,46.153,4.926,6,Rural à habitat dispersé,0.0,communes non pôle,NaN,https://fr.wikipedia.org/wiki/fr:L'Abergement-...,https://villedereve.fr/ville/01001-l-abergemen...
1,1,01002,L'Abergement-de-Varey,Abergement-de-Varey,à Abergement-de-Varey,de l'Abergement-de-Varey,l-abergement-de-varey,L'ABERGEMENT-DE-VAREY,COM,commune,...,5.423,46.009,5.428,6,Rural à habitat dispersé,0.0,communes non pôle,"Abergementais, Abergementaises",https://fr.wikipedia.org/wiki/fr:L'Abergement-...,https://villedereve.fr/ville/01002-l-abergemen...
2,2,01004,Ambérieu-en-Bugey,Ambérieu-en-Bugey,à Ambérieu-en-Bugey,d'Ambérieu-en-Bugey,amberieu-en-bugey,AMBÉRIEU-EN-BUGEY,COM,commune,...,5.360,45.961,5.373,2,Centres urbains intermédiaires,3.0,centres structurants d'équipements et de services,"Ambarrois, Ambarroises",https://fr.wikipedia.org/wiki/fr:Ambérieu-en-B...,https://villedereve.fr/ville/01004-amberieu-en...
3,3,01005,Ambérieux-en-Dombes,Ambérieux-en-Dombes,à Ambérieux-en-Dombes,d'Ambérieux-en-Dombes,amberieux-en-dombes,AMBÉRIEUX-EN-DOMBES,COM,commune,...,4.903,45.996,4.912,5,Bourgs ruraux,1.0,centres locaux d'équipements et de services,Ambarrois,https://fr.wikipedia.org/wiki/fr:Ambérieux-en-...,https://villedereve.fr/ville/01005-amberieux-e...
4,4,01006,Ambléon,Ambléon,à Ambléon,d'Ambléon,ambleon,AMBLÉON,COM,commune,...,5.601,45.750,5.594,6,Rural à habitat dispersé,0.0,communes non pôle,Ambléonais,https://fr.wikipedia.org/wiki/fr:Ambléon,https://villedereve.fr/ville/01006-ambleon
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34930,34930,97613,M'Tsangamouji,M'Tsangamouji,à M'Tsangamouji,de M'Tsangamouji,m-tsangamouji,M'TSANGAMOUJI,COM,commune,...,45.084,-12.751,45.087,3,Petites villes,NaN,NaN,NaN,https://fr.wikipedia.org/wiki/fr:M'Tsangamouji,https://villedereve.fr/ville/97613-m-tsangamouji
34931,34931,97614,Ouangani,Ouangani,à Ouangani,d'Ouangani,ouangani,OUANGANI,COM,commune,...,45.139,-12.837,45.138,3,Petites villes,NaN,NaN,NaN,https://fr.wikipedia.org/wiki/fr:Ouangani,https://villedereve.fr/ville/97614-ouangani
34932,34932,97615,Pamandzi,Pamandzi,à Pamandzi,de Pamandzi,pamandzi,PAMANDZI,COM,commune,...,45.275,-12.796,45.284,2,Centres urbains intermédiaires,NaN,NaN,Pamandziens,https://fr.wikipedia.org/wiki/fr:Pamandzi,https://villedereve.fr/ville/97615-pamandzi
34933,34933,97616,Sada,Sada,à Sada,de Sada,sada,SADA,COM,commune,...,45.106,-12.861,45.119,2,Centres urbains intermédiaires,NaN,NaN,Sadois,https://fr.wikipedia.org/wiki/fr:Sada (Mayotte),https://villedereve.fr/ville/97616-sada
34934,34934,97617,Tsingoni,Tsingoni,à Tsingoni,de Tsingoni,tsingoni,TSINGONI,COM,commune,...,45.105,-12.782,45.134,2,Centres urbains intermédiaires,NaN,NaN,NaN,https://fr.wikipedia.org/wiki/fr:Tsingoni,https://villedereve.fr/ville/97617-tsingoni

In [ ]:
import pandas as pd

df = pd.read_csv('raw/immo_data.csv')
columns = ['adresse_numero', 'adresse_suffixe', 'adresse_nom_voie', 'adresse_code_voie', 'code_postal', 'code_commune', 'nom_commune', 'code_departement', 'ancien_code_commune', 'ancien_nom_commune']

df[columns]

C:\Users\Utilisateur\AppData\Local\Temp\ipykernel_17420\2762195721.py:3: DtypeWarning: Columns (18,19,21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('raw/immo_data.csv')

,adresse_numero,adresse_suffixe,adresse_nom_voie,adresse_code_voie,code_postal,code_commune,nom_commune,code_departement,ancien_code_commune,ancien_nom_commune
0,NaN,NaN,SAINT JULIEN,B064,1560.0,1367,Saint-Julien-sur-Reyssouze,1,NaN,NaN
1,NaN,NaN,A LA PEROUSE,B188,1250.0,1125,Corveissiat,1,NaN,NaN
2,NaN,NaN,A LA PEROUSE,B188,1250.0,1125,Corveissiat,1,NaN,NaN
3,NaN,NaN,AUX COMMUNS,B079,1250.0,1125,Corveissiat,1,NaN,NaN
4,NaN,NaN,EN COMBARNAUD,B033,1250.0,1408,Simandre-sur-Suran,1,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
49995,121.0,NaN,CHE DU LERY,0092,3700.0,3271,Serbannes,3,NaN,NaN
49996,NaN,NaN,CHE DU LERY,0092,3700.0,3271,Serbannes,3,NaN,NaN
49997,4.0,NaN,ALL MAURICE RAVEL,1003,3500.0,3254,Saint-Pourçain-sur-Sioule,3,NaN,NaN
49998,5247.0,NaN,COMBACHOL,B032,3450.0,3135,Lalizolle,3,NaN,NaN
49999,3.0,NaN,LE PESSELAN,B185,3330.0,3022,Bellenaves,3,NaN,NaN