In [14]:
import pandas as pd
from pathlib import Path
import os

BASE_DIR = Path().resolve().parents[2]

csv_2020 = BASE_DIR / 'flatfiles' / 'data_vf' / 'data_2020.csv'
csv_2021 = BASE_DIR / 'flatfiles' / 'data_vf' / 'data_2021.csv'
csv_2022 = BASE_DIR / 'flatfiles' / 'data_vf' / 'data_2022.csv'
csv_2023 = BASE_DIR / 'flatfiles' / 'data_vf' / 'data_2023.csv'
csv_2024 = BASE_DIR / 'flatfiles' / 'data_vf' / 'data_2024.csv'
csv_2025 = BASE_DIR / 'flatfiles' / 'data_vf' / 'data_2025.csv'

csv_communes_2022 = BASE_DIR / 'flatfiles' / 'commune_france' / 'communes_france_2022.csv'
csv_communes_2023 = BASE_DIR / 'flatfiles' / 'commune_france' / 'communes_france_2023.csv'
csv_communes_2024 = BASE_DIR / 'flatfiles' / 'commune_france' / 'communes_france_2024.csv'
csv_communes_2025 = BASE_DIR / 'flatfiles' / 'commune_france' / 'communes_france_2025.csv'

csv_taxe_fonciere = BASE_DIR / 'flatfiles' / 'taxe_fonciere_chefs_lieux_2021_2024.csv'

In [2]:
# Création des DataFrames
df_2020 = pd.read_csv(csv_2020)

C:\Users\fatim\AppData\Local\Temp\ipykernel_17292\2454854937.py:2: DtypeWarning: Columns (8,10,12,14,16,17,18,20,22,35,36) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2020 = pd.read_csv(csv_2020)

In [11]:
df_2021 = pd.read_csv(csv_2021)

C:\Users\fatim\AppData\Local\Temp\ipykernel_17292\4291009226.py:1: DtypeWarning: Columns (10,12,14,17,18,20,22,24,35,36) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2021 = pd.read_csv(csv_2021)

In [13]:
df_2022 = pd.read_csv(csv_2022)

C:\Users\fatim\AppData\Local\Temp\ipykernel_17292\66118111.py:1: DtypeWarning: Columns (10,12,14,16,17,18,20,22,35,36) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2022 = pd.read_csv(csv_2022)

In [15]:
df_2023 = pd.read_csv(csv_2023)

C:\Users\fatim\AppData\Local\Temp\ipykernel_17292\2045294576.py:1: DtypeWarning: Columns (8,10,12,14,16,17,18,20,22,26,35,36) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2023 = pd.read_csv(csv_2023)

In [4]:
df_2024 = pd.read_csv(csv_2024)

C:\Users\fatim\AppData\Local\Temp\ipykernel_17212\401764953.py:1: DtypeWarning: Columns (10,12,14,16,17,18,20,22,24,35,36) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2024 = pd.read_csv(csv_2024)

In [8]:
df_2025 = pd.read_csv(csv_2025)

C:\Users\fatim\AppData\Local\Temp\ipykernel_17212\1456618700.py:1: DtypeWarning: Columns (10,12,14,16,17,18,20,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2025 = pd.read_csv(csv_2025)

In [6]:
cols = [
    'date_mutation',
    'valeur_fonciere',
    'surface_reelle_bati',
    'code_commune',
    'type_local',
    'nombre_pieces_principales',
    'longitude',
    'latitude',
    'code_postal',
    'id_mutation'
]

import os
import pandas as pd

def prepare_and_agg(df):

    os.makedirs('raw', exist_ok=True)
    
    df = df[cols].copy()
    df['prix_m2'] = df['valeur_fonciere'] / df['surface_reelle_bati']
    df['annee'] = pd.to_datetime(df['date_mutation']).dt.year
    
    df_agg = df.groupby(['code_commune', 'annee']).agg({
        'prix_m2': 'mean',
        'surface_reelle_bati': 'mean',
        'id_mutation': 'count'
    }).rename(columns={'id_mutation':'nb_ventes'}).reset_index()
    
    annee= df['annee'].unique()[0] 
    output_path = os.path.join('raw', f'csv_agg_{annee}.csv')
    
    df_agg.to_csv(output_path, index=False, sep=';', encoding='utf-8')
    
    print(f"Fichier CSV enregistré ici : {output_path}")
    return df_agg

In [9]:
df_agg_2020 = prepare_and_agg(df_2020)

Fichier CSV enregistré ici : raw\csv_agg_2020.csv

In [12]:
df_agg_2021 = prepare_and_agg(df_2021)

Fichier CSV enregistré ici : raw\csv_agg_2021.csv

In [14]:
df_agg_2022 = prepare_and_agg(df_2022)

Fichier CSV enregistré ici : raw\csv_agg_2022.csv

In [16]:
df_agg_2023 = prepare_and_agg(df_2023)

Fichier CSV enregistré ici : raw\csv_agg_2023.csv

In [7]:
df_agg_2024 = prepare_and_agg(df_2024)

Fichier CSV enregistré ici : raw\csv_agg_2024.csv

In [9]:
df_agg_2025 = prepare_and_agg(df_2025)

Fichier CSV enregistré ici : raw\csv_agg_2025.csv

In [23]:
#df_agg_2020 = pd.read_csv(r'raw\csv_agg_2020.csv', sep=';')
#df_agg_2021 = pd.read_csv(r'raw\csv_agg_2021.csv', sep=';')
df_agg_2022 = pd.read_csv(r'raw\csv_agg_2022.csv', sep=';')
df_agg_2023 = pd.read_csv(r'raw\csv_agg_2023.csv', sep=';')
df_agg_2024 = pd.read_csv(r'raw\csv_agg_2024.csv', sep=';')
#df_agg_2025 = pd.read_csv(r'raw\csv_agg_2025.csv', sep=';')

# Concaténer tous les DataFrames
df_agg_all = pd.concat([df_agg_2022, df_agg_2023, df_agg_2024
], ignore_index=True)

In [24]:
df_agg_all.head()

  code_commune  annee       prix_m2  surface_reelle_bati  nb_ventes
0         1001   2022   2930.586507           131.466667         43
1         1002   2022   2575.603876           135.333333         24
2         1004   2022   3452.219201           234.213836       1028
3         1005   2022  11225.915649            99.393939        151
4         1006   2022   1421.052632            95.000000         15

In [25]:
output_path = os.path.join('raw', f'csv_agg_all.csv')
df_agg_all.to_csv(output_path, index=False, sep=';', encoding='utf-8')

In [26]:
df_communes_2022 = pd.read_csv(csv_communes_2022)
df_communes_2023 = pd.read_csv(csv_communes_2023)
df_communes_2024 = pd.read_csv(csv_communes_2024)
#df_communes_2025 = pd.read_csv(csv_communes_2025)

df_communes_2022['annee'] = 2022
df_communes_2023['annee'] = 2023
df_communes_2024['annee'] = 2024
#df_communes_2025['annee'] = 2025

df_communes_all = pd.concat([
    df_communes_2022, df_communes_2023, df_communes_2024
], ignore_index=True)

output_path = os.path.join('raw', f'csv_communes_all.csv')
df_communes_all.to_csv(output_path, index=False, sep=';', encoding='utf-8')

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Utilisateur\\Desktop\\Geologis\\GeoLogis\\flatfiles\\commune_france\\communes_france_2022.csv'

In [178]:
df_communes_all.columns

Index(['Unnamed: 0', 'code_insee', 'nom_standard', 'nom_sans_pronom', 'nom_a',
       'nom_de', 'nom_sans_accent', 'nom_standard_majuscule', 'typecom',
       'typecom_texte', 'reg_code', 'reg_nom', 'dep_code', 'dep_nom',
       'canton_code', 'canton_nom', 'epci_code', 'epci_nom', 'academie_code',
       'academie_nom', 'code_postal', 'codes_postaux', 'zone_emploi',
       'code_insee_centre_zone_emploi', 'population', 'superficie_hectare',
       'superficie_km2', 'densite', 'altitude_moyenne', 'altitude_minimale',
       'altitude_maximale', 'latitude_mairie', 'longitude_mairie',
       'latitude_centre', 'longitude_centre', 'grille_densite', 'gentile',
       'url_wikipedia', 'url_villedereve', 'annee'],
      dtype='object')

In [179]:
cols_commune = [
    'annee','code_insee', 'nom_standard', 'code_postal',
    'dep_code', 'dep_nom', 'reg_code', 'reg_nom',
    'population', 'densite', 'superficie_km2',
    'latitude_centre', 'longitude_centre','zone_emploi'
]

df_communes_all = df_communes_all[cols_commune]

In [180]:
df_communes_all = df_communes_all[
    df_communes_all['code_insee'].notna() &
    ~df_communes_all['code_insee'].astype(str).str.startswith(('97', '98', '2A', '2B'))
]

df_communes_all['code_insee'] = df_communes_all['code_insee'].astype(int)

In [181]:
df_communes_all.head()

,annee,code_insee,nom_standard,code_postal,dep_code,dep_nom,reg_code,reg_nom,population,densite,superficie_km2,latitude_centre,longitude_centre,zone_emploi
0,2022,1001,L'Abergement-Clémenciat,1400,01,Ain,84,Auvergne-Rhône-Alpes,779,48.7,16,46.153,4.926,8405.0
1,2022,1002,L'Abergement-de-Varey,1640,01,Ain,84,Auvergne-Rhône-Alpes,256,27.1,9,46.009,5.428,8405.0
2,2022,1004,Ambérieu-en-Bugey,1500,01,Ain,84,Auvergne-Rhône-Alpes,14134,570.5,24,45.961,5.373,8405.0
3,2022,1005,Ambérieux-en-Dombes,1330,01,Ain,84,Auvergne-Rhône-Alpes,1751,106.1,16,45.996,4.912,8434.0
4,2022,1006,Ambléon,1300,01,Ain,84,Auvergne-Rhône-Alpes,112,18.9,6,45.750,5.594,8404.0

In [182]:
df_agg_all = df_agg_all[
    df_agg_all['code_commune'].notna() &
    ~df_agg_all['code_commune'].astype(str).str.startswith(('97', '98', '2A', '2B'))
]

df_agg_all['code_commune'] = df_agg_all['code_commune'].astype(int)

In [183]:
df_agg_all.head()

   code_commune  annee       prix_m2  surface_reelle_bati  nb_ventes
0          1001   2022   2930.586507           131.466667         43
1          1002   2022   2575.603876           135.333333         24
2          1004   2022   3452.219201           234.213836       1028
3          1005   2022  11225.915649            99.393939        151
4          1006   2022   1421.052632            95.000000         15

In [184]:
df_merged = df_agg_all.merge(df_communes_all,
                              left_on=['code_commune', 'annee'],
                              right_on=['code_insee', 'annee'],
                              how='left')

In [185]:
df_merged.head()

,code_commune,annee,prix_m2,surface_reelle_bati,nb_ventes,code_insee,nom_standard,code_postal,dep_code,dep_nom,reg_code,reg_nom,population,densite,superficie_km2,latitude_centre,longitude_centre,zone_emploi
0,1001,2022,2930.586507,131.466667,43,1001.0,L'Abergement-Clémenciat,1400.0,01,Ain,84.0,Auvergne-Rhône-Alpes,779.0,48.7,16.0,46.153,4.926,8405.0
1,1002,2022,2575.603876,135.333333,24,1002.0,L'Abergement-de-Varey,1640.0,01,Ain,84.0,Auvergne-Rhône-Alpes,256.0,27.1,9.0,46.009,5.428,8405.0
2,1004,2022,3452.219201,234.213836,1028,1004.0,Ambérieu-en-Bugey,1500.0,01,Ain,84.0,Auvergne-Rhône-Alpes,14134.0,570.5,24.0,45.961,5.373,8405.0
3,1005,2022,11225.915649,99.393939,151,1005.0,Ambérieux-en-Dombes,1330.0,01,Ain,84.0,Auvergne-Rhône-Alpes,1751.0,106.1,16.0,45.996,4.912,8434.0
4,1006,2022,1421.052632,95.000000,15,1006.0,Ambléon,1300.0,01,Ain,84.0,Auvergne-Rhône-Alpes,112.0,18.9,6.0,45.750,5.594,8404.0

In [27]:
# Merge avec taxe foncière
df_taxe_fonciere = pd.read_csv(csv_taxe_fonciere)
df_taxe_fonciere.head(10)

,dept,nom_commune,insee_com,annee_cible,annee_source,est_fallback,taux_global_tfb,taux_global_tfnb,taux_plein_teom,taux_global_th
0,01,Bourg-en-Bresse,01053,2021,2021,False,38.81,118.52,9.95,28.64
1,01,Bourg-en-Bresse,01053,2022,2022,False,38.82,118.47,9.95,28.63
2,01,Bourg-en-Bresse,01053,2023,2023,False,38.82,118.53,9.95,28.62
3,01,Bourg-en-Bresse,01053,2024,2024,False,40.25,121.52,9.95,29.62
4,02,Laon,02408,2021,2021,False,64.73,76.43,NaN,36.77
5,02,Laon,02408,2022,2022,False,64.73,76.43,NaN,36.77
6,02,Laon,02408,2023,2023,False,64.73,76.43,NaN,36.77
7,02,Laon,02408,2024,2024,False,65.56,77.50,NaN,37.79
8,03,Moulins,03190,2021,2021,False,41.70,85.00,12.04,28.87
9,03,Moulins,03190,2022,2022,False,41.70,85.00,11.93,28.87

In [190]:
df_merged = df_merged.merge(
    df_taxe_fonciere[['dept', 'annee_cible', 'taux_global_tfb', 'taux_global_tfnb', 'taux_plein_teom', 'taux_global_th']],
    left_on=['dep_code', 'annee'],
    right_on=['dept', 'annee_cible'],
    how='left'
)

In [22]:
df_merged

NameError: name 'df_merged' is not defined

In [192]:
output_path = os.path.join('raw', f'csv_merge_all.csv')
df_merged.to_csv(output_path, index=False, sep=';', encoding='utf-8')

In [16]:
df = pd.read_csv(r'raw\csv_merge_all.csv', sep=';')

In [4]:
df.columns

Index(['code_commune', 'annee', 'prix_m2', 'surface_reelle_bati', 'nb_ventes',
       'code_insee', 'nom_standard', 'code_postal', 'dep_code', 'dep_nom',
       'reg_code', 'reg_nom', 'population', 'densite', 'superficie_km2',
       'latitude_centre', 'longitude_centre', 'zone_emploi', 'dept',
       'annee_cible', 'taux_global_tfb', 'taux_global_tfnb', 'taux_plein_teom',
       'taux_global_th'],
      dtype='object')

In [ ]:
vf_annee = df.groupby(['annee', 'code_commune']).agg(
    prix_m2=('prix_m2', 'mean'),
    nom_commune=('nom_standard', 'first'),
    dep_code=('dep_code', 'first'),
    dep_nom=('dep_nom', 'first'),
    reg_code=('reg_code', 'first'),
    reg_nom=('reg_nom', 'first'),
    code_postal=('code_postal', 'first'),
    population=('population', 'first'),
    densite=('densite', 'first'),
    superficie_km2=('superficie_km2', 'first'),
    zone_emploi=('zone_emploi', 'first'),
    taux_global_tfb=('taux_global_tfb', 'first'),
    taux_global_tfnb=('taux_global_tfnb', 'first'),
    taux_plein_teom=('taux_plein_teom', 'first'),
    taux_global_th=('taux_global_th', 'first'),
    nb_ventes=('nb_ventes', 'first')

).reset_index()


def market_trend(x, seuil=0.02): 
    if x > seuil:
        return 'hausse'
    elif x < -seuil:
        return 'baisse'
    else:
        return 'stable'
    

vf_annee['variation_pct'] = vf_annee.groupby('code_commune')['prix_m2'].pct_change()

vf_annee['y'] = vf_annee['variation'].apply(market_trend)

In [9]:
vf_annee.columns

Index(['annee', 'code_commune', 'prix_m2', 'nom_commune', 'dep_code',
       'dep_nom', 'reg_code', 'reg_nom', 'code_postal', 'population',
       'densite', 'superficie_km2', 'zone_emploi', 'taux_global_tfb',
       'taux_global_tfnb', 'taux_plein_teom', 'taux_global_th', 'nb_ventes',
       'variation', 'y'],
      dtype='object')

In [10]:
vf_annee = vf_annee.drop(columns=['variation'])

In [11]:
vf_annee

,annee,code_commune,prix_m2,nom_commune,dep_code,dep_nom,reg_code,reg_nom,code_postal,population,densite,superficie_km2,zone_emploi,taux_global_tfb,taux_global_tfnb,taux_plein_teom,taux_global_th,nb_ventes,y
0,2022,1001,2930.586507,L'Abergement-Clémenciat,1.0,Ain,84.0,Auvergne-Rhône-Alpes,1400.0,779.0,48.70,16.0,8405.0,38.82,118.47,9.95,28.63,43,stable
1,2022,1002,2575.603876,L'Abergement-de-Varey,1.0,Ain,84.0,Auvergne-Rhône-Alpes,1640.0,256.0,27.10,9.0,8405.0,38.82,118.47,9.95,28.63,24,stable
2,2022,1004,3452.219201,Ambérieu-en-Bugey,1.0,Ain,84.0,Auvergne-Rhône-Alpes,1500.0,14134.0,570.50,24.0,8405.0,38.82,118.47,9.95,28.63,1028,stable
3,2022,1005,11225.915649,Ambérieux-en-Dombes,1.0,Ain,84.0,Auvergne-Rhône-Alpes,1330.0,1751.0,106.10,16.0,8434.0,38.82,118.47,9.95,28.63,151,stable
4,2022,1006,1421.052632,Ambléon,1.0,Ain,84.0,Auvergne-Rhône-Alpes,1300.0,112.0,18.90,6.0,8404.0,38.82,118.47,9.95,28.63,15,stable
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97153,2024,95676,4983.643482,Villers-en-Arthies,95.0,Val-d'Oise,11.0,Île-de-France,95510.0,490.0,59.39,8.0,1101.0,NaN,NaN,NaN,NaN,34,hausse
97154,2024,95678,4561.985168,Villiers-Adam,95.0,Val-d'Oise,11.0,Île-de-France,95840.0,857.0,87.27,10.0,1101.0,NaN,NaN,NaN,NaN,26,hausse
97155,2024,95680,5987.958694,Villiers-le-Bel,95.0,Val-d'Oise,11.0,Île-de-France,95400.0,28636.0,3922.74,7.0,1112.0,NaN,NaN,NaN,NaN,869,baisse
97156,2024,95682,4238.626536,Villiers-le-Sec,95.0,Val-d'Oise,11.0,Île-de-France,95720.0,193.0,59.20,3.0,1112.0,NaN,NaN,NaN,NaN,7,baisse
97157,2024,95690,2606.189921,Wy-dit-Joli-Village,95.0,Val-d'Oise,11.0,Île-de-France,95420.0,330.0,39.43,8.0,1101.0,NaN,NaN,NaN,NaN,21,baisse

In [15]:
output_path = os.path.join('raw', f'csv_full.csv')
vf_annee.to_csv(output_path, index=False, sep=';', encoding='utf-8')

In [17]:
df = pd.read_csv(r'raw\csv_merge_all.csv', sep=';')

#### Merge par code_postal

In [29]:
df_vf = pd.read_csv(r'raw\csv_agg_all.csv', sep=';')
df_comm = pd.read_csv(r'raw\csv_communes_all.csv', sep=';')

C:\Users\Utilisateur\AppData\Local\Temp\ipykernel_6140\3494460096.py:2: DtypeWarning: Columns (1,12,14,16,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df_comm = pd.read_csv(r'raw\csv_communes_all.csv', sep=';')

In [31]:
df_comm.columns

Index(['Unnamed: 0', 'code_insee', 'nom_standard', 'nom_sans_pronom', 'nom_a',
       'nom_de', 'nom_sans_accent', 'nom_standard_majuscule', 'typecom',
       'typecom_texte', 'reg_code', 'reg_nom', 'dep_code', 'dep_nom',
       'canton_code', 'canton_nom', 'epci_code', 'epci_nom', 'academie_code',
       'academie_nom', 'code_postal', 'codes_postaux', 'zone_emploi',
       'code_insee_centre_zone_emploi', 'population', 'superficie_hectare',
       'superficie_km2', 'densite', 'altitude_moyenne', 'altitude_minimale',
       'altitude_maximale', 'latitude_mairie', 'longitude_mairie',
       'latitude_centre', 'longitude_centre', 'grille_densite', 'gentile',
       'url_wikipedia', 'url_villedereve', 'annee'],
      dtype='object')

In [32]:
df_vf.columns

Index(['code_commune', 'annee', 'prix_m2', 'surface_reelle_bati', 'nb_ventes'], dtype='object')

In [35]:
df_vf['code_commune'] = df_vf['code_commune'].astype(str).str.zfill(5)
df_comm['code_insee'] = df_comm['code_insee'].astype(str).str.zfill(5)

df_merged = df_vf.merge(df_comm,
                              left_on=['code_commune', 'annee'],
                              right_on=['code_insee', 'annee'],
                              how='left')

In [36]:
df_merged.head()

,code_commune,annee,prix_m2,surface_reelle_bati,nb_ventes,Unnamed: 0,code_insee,nom_standard,nom_sans_pronom,nom_a,...,altitude_minimale,altitude_maximale,latitude_mairie,longitude_mairie,latitude_centre,longitude_centre,grille_densite,gentile,url_wikipedia,url_villedereve
0,01001,2022,2930.586507,131.466667,43,0.0,01001,L'Abergement-Clémenciat,Abergement-Clémenciat,à Abergement-Clémenciat,...,206.0,272.0,46.153,4.926,46.153,4.926,Rural à habitat dispersé,NaN,https://fr.wikipedia.org/wiki/fr:L'Abergement-...,https://villedereve.fr/ville/01001-l-abergemen...
1,01002,2022,2575.603876,135.333333,24,1.0,01002,L'Abergement-de-Varey,Abergement-de-Varey,à Abergement-de-Varey,...,290.0,748.0,46.009,5.428,46.009,5.428,Rural à habitat dispersé,"Abergementais, Abergementaises",https://fr.wikipedia.org/wiki/fr:L'Abergement-...,https://villedereve.fr/ville/01002-l-abergemen...
2,01004,2022,3452.219201,234.213836,1028,2.0,01004,Ambérieu-en-Bugey,Ambérieu-en-Bugey,à Ambérieu-en-Bugey,...,237.0,753.0,45.961,5.373,45.961,5.373,Centres urbains intermédiaires,"Ambarrois, Ambarroises",https://fr.wikipedia.org/wiki/fr:Ambérieu-en-B...,https://villedereve.fr/ville/01004-amberieu-en...
3,01005,2022,11225.915649,99.393939,151,3.0,01005,Ambérieux-en-Dombes,Ambérieux-en-Dombes,à Ambérieux-en-Dombes,...,265.0,302.0,45.996,4.912,45.996,4.912,Bourgs ruraux,Ambarrois,https://fr.wikipedia.org/wiki/fr:Ambérieux-en-...,https://villedereve.fr/ville/01005-amberieux-e...
4,01006,2022,1421.052632,95.000000,15,4.0,01006,Ambléon,Ambléon,à Ambléon,...,330.0,940.0,45.750,5.594,45.750,5.594,Rural à habitat dispersé,Ambléonais,https://fr.wikipedia.org/wiki/fr:Ambléon,https://villedereve.fr/ville/01006-ambleon

In [38]:
df_taxe_fonciere = pd.read_csv(csv_taxe_fonciere) 
df_taxe_fonciere.head(10)

df_merged['dep_code'] = df_merged['dep_code'].astype(str).str.zfill(2)
df_taxe_fonciere['dept'] = df_taxe_fonciere['dept'].astype(str).str.zfill(2)

df_merged['annee'] = df_merged['annee'].astype(int)
df_taxe_fonciere['annee_cible'] = df_taxe_fonciere['annee_cible'].astype(int)

In [39]:
df_merged = df_merged.merge(
    df_taxe_fonciere[['dept', 'annee_cible', 'taux_global_tfb', 'taux_global_tfnb', 'taux_plein_teom', 'taux_global_th']],
    left_on=['dep_code', 'annee'],
    right_on=['dept', 'annee_cible'],
    how='left'
)

In [43]:
df_merged[['dept', 'annee_cible', 'taux_global_tfb', 'taux_global_tfnb', 'taux_plein_teom', 'taux_global_th']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99629 entries, 0 to 99628
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   dept              99616 non-null  object
 1   annee_cible       99616 non-null  float64
 2   taux_global_tfb   99616 non-null  float64
 3   taux_global_tfnb  99616 non-null  float64
 4   taux_plein_teom   93000 non-null  float64
 5   taux_global_th    99616 non-null  float64
dtypes: float64(5), object(1)
memory usage: 4.6+ MB

In [46]:
df_merged.columns

Index(['code_commune', 'annee', 'prix_m2', 'surface_reelle_bati', 'nb_ventes',
       'Unnamed: 0', 'code_insee', 'nom_standard', 'nom_sans_pronom', 'nom_a',
       'nom_de', 'nom_sans_accent', 'nom_standard_majuscule', 'typecom',
       'typecom_texte', 'reg_code', 'reg_nom', 'dep_code', 'dep_nom',
       'canton_code', 'canton_nom', 'epci_code', 'epci_nom', 'academie_code',
       'academie_nom', 'code_postal', 'codes_postaux', 'zone_emploi',
       'code_insee_centre_zone_emploi', 'population', 'superficie_hectare',
       'superficie_km2', 'densite', 'altitude_moyenne', 'altitude_minimale',
       'altitude_maximale', 'latitude_mairie', 'longitude_mairie',
       'latitude_centre', 'longitude_centre', 'grille_densite', 'gentile',
       'url_wikipedia', 'url_villedereve', 'dept', 'annee_cible',
       'taux_global_tfb', 'taux_global_tfnb', 'taux_plein_teom',
       'taux_global_th'],
      dtype='object')

In [47]:
vf_annee = df_merged.groupby(['annee', 'code_postal']).agg(
    prix_m2=('prix_m2', 'mean'),
    dep_code=('dep_code', 'first'),
    dep_nom=('dep_nom', 'first'),
    reg_code=('reg_code', 'first'),
    reg_nom=('reg_nom', 'first'),
    population=('population', 'sum'),
    superficie_km2=('superficie_km2', 'sum'),  
    zone_emploi=('zone_emploi', 'first'),
    taux_global_tfb=('taux_global_tfb', 'mean'),
    taux_global_tfnb=('taux_global_tfnb', 'mean'),
    taux_plein_teom=('taux_plein_teom', 'mean'),
    taux_global_th=('taux_global_th', 'mean'),
    nb_ventes=('nb_ventes', 'sum')
).reset_index()

vf_annee['variation'] = vf_annee.groupby('code_postal')['prix_m2'].diff()

def market_trend(x):
    if x > 0:
        return 'hausse'
    elif x < 0:
        return 'baisse'
    else:
        return 'stable'
    
vf_annee['y'] = vf_annee['variation'].apply(market_trend)
vf_annee = vf_annee.drop(columns=['variation'])

In [48]:
vf_annee.columns

Index(['annee', 'code_postal', 'prix_m2', 'dep_code', 'dep_nom', 'reg_code',
       'reg_nom', 'population', 'superficie_km2', 'zone_emploi',
       'taux_global_tfb', 'taux_global_tfnb', 'taux_plein_teom',
       'taux_global_th', 'nb_ventes', 'y'],
      dtype='object')

In [1]:
output_path = os.path.join('raw', f'csv_full_post.csv')
vf_annee.to_csv(output_path, index=False, sep=';', encoding='utf-8')

NameError: name 'os' is not defined